'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Win10_Privacy.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_rdy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_rdy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property paypal_donate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paypal_donate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 127.0.0.1 vortex.data.microsoft.com
        '''127.0.0.1 vortex-win.data.microsoft.com
        '''127.0.0.1 telecommand.telemetry.microsoft.com
        '''127.0.0.1 telecommand.telemetry.microsoft.com.nsatc.net
        '''127.0.0.1 oca.telemetry.microsoft.com
        '''127.0.0.1 oca.telemetry.microsoft.com.nsatc.net
        '''127.0.0.1 sqm.telemetry.microsoft.com
        '''127.0.0.1 sqm.telemetry.microsoft.com.nsatc.net
        '''127.0.0.1 watson.telemetry.microsoft.com
        '''127.0.0.1 watson.telemetry.microsoft.com.nsatc.net
        '''127.0.0.1 redir.metaservices.microsoft.com
        '''127.0.0.1 choice [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property strings_of_hosts() As String
            Get
                Return ResourceManager.GetString("strings_of_hosts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 127.0.0.1 ui.skype.com
        '''127.0.0.1 www.msftncsi.com
        '''127.0.0.1 msftncsi.com
        '''127.0.0.1 apps.skype.com
        '''127.0.0.1 pricelist.skype.com
        '''127.0.0.1 s.gateway.messenger.live.com.
        '''</summary>
        Friend ReadOnly Property strings_of_hosts_skype() As String
            Get
                Return ResourceManager.GetString("strings_of_hosts_skype", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
